lane :build_and_release_to_play_store do |options|
    # Bundle the app
    gradle(
        task: 'bundle',
        project_dir: "android/"
    )

    # Upload to Play Store's Internal Testing
    upload_to_play_store(
        package_name: 'com.demoapp',
        track: "internal",
        json_key: "./android/app/google-private-key.json",
        aab: "./android/app/build/outputs/bundle/release/app-release.aab"
    )
end