name: Build Android and iOS
on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn --frozen-lockfile
      - name: Run lint
        run: |
          yarn test:lint
      - name: Run unit tests
        run: |
          yarn test:unit
