name: Publish React Native App to Play Store
on:
  release:
    types: [published]

jobs:
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: Setup react-native kernel and increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Install Fastlane
        run: bundle install

      - name: Install npm dependencies
        run: yarn --frozen-lockfile

      - name: Jetifier AndroidX transition
        run: npx jetify

      - name: Decrypt keystore and Google Credential
        run: sh ./scripts/android-gpg-decrypt.sh
        env:
          ENCRYPT_PASSWORD: ${{ secrets.ENCRYPT_PASSWORD }}

      - name: Dump secrets to .env
        run: env > .env
        # If we need to add other env variables :
        # env:
        #   OTHER_ENV_VAR: ${{ secrets.OTHER_ENV_VAR }}

      - name: Build bundle
        run: bundle exec fastlane build_bundle versionName:${{ github.event.release.tag_name }}
        env:
          VERSION_NAME: ${{ github.event.release.tag_name }}
          GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/

      - name: Upload to PlayStore
        run: bundle exec fastlane release_to_play_store versionName:${{ github.event.release.tag_name }}
        env:
          VERSION_NAME: ${{ github.event.release.tag_name }}
          GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
