name: Publish React Native App to Play Store
on:
  release:
    types: [published]

jobs:
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: Setup react-native kernel and increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Install Fastlane
        run: bundle install

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install node modules
        run: yarn --frozen-lockfile --cache-folder="~/.npm"

      - name: Jetifier AndroidX transition
        run: npx jetify

      - name: Decrypt keystore and Google Credential
        run: sh ./scripts/android-gpg-decrypt.sh
        env:
          ENCRYPT_PASSWORD: ${{ secrets.ENCRYPT_PASSWORD }}

      - name: Dump secrets to .env
        run: env > .env
        # If we need to add other env variables :
        # env:
        #   OTHER_ENV_VAR: ${{ secrets.OTHER_ENV_VAR }}

      - name: Delete previous builds
        run: bundle exec fastlane delete_builds

      - name: Build bundle
        run: bundle exec fastlane build_bundle versionName:${{ github.event.release.tag_name }}
        env:
          VERSION_NAME: ${{ github.event.release.tag_name }}
          GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload to PlayStore
        run: bundle exec fastlane release_to_playstore_internal_testing versionName:${{ github.event.release.tag_name }}
        env:
          VERSION_NAME: ${{ github.event.release.tag_name }}
          GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
